# Generated by Django 3.0.3 on 2020-02-14 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('contact_type', models.CharField(choices=[('PF', 'Natural Person'), ('PJ', 'Legal entity')], default='PF', max_length=2, verbose_name='Type')),
                ('first_name', models.CharField(help_text='First name, or legal name', max_length=150, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Last name')),
                ('full_name', models.CharField(default='', editable=False, max_length=300, verbose_name='Full name')),
                ('language', models.CharField(choices=[('ca', 'Catalan'), ('es', 'Spanish'), ('en', 'English')], default='es', max_length=2, verbose_name='Preferred language')),
                ('web_address', models.URLField(blank=True, default='', verbose_name='Página web')),
                ('assignee', models.ForeignKey(editable=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='ContactPostalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el dato es vigente o no', verbose_name='Vigente')),
                ('internal_note', models.TextField(blank=True, default='', verbose_name='Nota interna')),
                ('address_to', models.CharField(blank=True, default='', help_text='To whom shall mailings be addresses', max_length=150, verbose_name='Address to')),
                ('address_line1', models.CharField(max_length=150, verbose_name='Address line')),
                ('address_line2', models.CharField(blank=True, default='', max_length=150, verbose_name='Address line (extra)')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal code')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='Country')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_addresses', to='contacts.Contact')),
            ],
            options={
                'verbose_name': 'Postal address',
                'verbose_name_plural': 'Postal addresses',
                'ordering': ('address_to', 'country'),
                'default_related_name': 'postal_addresses',
            },
        ),
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el dato es vigente o no', verbose_name='Vigente')),
                ('internal_note', models.TextField(blank=True, default='', verbose_name='Nota interna')),
                ('number', models.CharField(max_length=100, verbose_name='Number')),
                ('can_sms', models.BooleanField(default=False, help_text='Note if the number can receive SMS (if it can, not if it wants)', verbose_name='Handles SMS')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contacts.Contact')),
            ],
            options={
                'verbose_name': 'Phone number',
                'verbose_name_plural': 'Phone numbers',
                'ordering': ('number',),
                'default_related_name': 'phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='ContactEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el dato es vigente o no', verbose_name='Vigente')),
                ('internal_note', models.TextField(blank=True, default='', verbose_name='Nota interna')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_addresses', to='contacts.Contact')),
            ],
            options={
                'verbose_name': 'E-mail address',
                'verbose_name_plural': 'E-mail addresses',
                'ordering': ('email',),
                'default_related_name': 'email_addresses',
            },
        ),
    ]
